language: node_js
node_js:
  - "12.13.0"
install:
  - npm i
stages:
  - lint
jobs:
  include:
    - stage: lint
      script:
        # Lint all
        - npm run lint
    - stage: test
      script:
        # Lint all
        - npm run test