name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: node scripts/jsdoc2md.js
